web_hosts:
- domain: git.raumzeitlabor.de
  backend_host: 192.0.2.0 #RFC documentation IP-Address, placeholder to test ansible untill the git-backend actually has an IP-Address
  backend_port_ssl: 443
  backend_port_plain: 80

- domain: www.raumzeitlabor.de
  backend_host: 172.17.0.3
  backend_port_plain: 80
  default: true

- domain: rzl-homepage.raumzeitlabor.org
  backend_host: 172.17.0.3
  backend_port_plain: 80
  wildcard: true

- domain: raumzeitlabor.de #TODO: pass to 172.17.0.3 with termination
  backend_host: 172.17.0.2
  backend_port_ssl: 443
  backend_port_plain: 80

- domain: rzl.so
  backend_host: 172.17.0.3
  backend_port_plain: 80

- domain: www.rzl.so
  backend_host: 172.17.0.3
  backend_port_plain: 80

- domain: was.geht.im.rzl.so
  backend_host: 172.17.0.3
  backend_port_plain: 80

- domain: w.rzl.so
  backend_host: 172.17.0.5
  backend_port_plain: 80

- domain: wiki.raumzeitlabor.de
  backend_host: 172.17.0.5
  backend_port_plain: 80


